Machine Learning project for healthcare domain:
Problem statement - predicting that whether a patient has diabetes or not on the basis of the features we will provide to our machine learning model from the Pima Indians Diabetes dataset.  


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv('/content/diabetes.csv')

In [ ]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
x=data[['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']]
y=data['Outcome']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier      #by using KNN
knn=KNeighborsClassifier(n_neighbors=25)

In [ ]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=25)

In [ ]:
y_pred=knn.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_pred,y_test)
ac=accuracy_score(y_pred,y_test)

In [ ]:
print(ac)

0.7792207792207793


In [ ]:
print(cm)

[[91 19]
 [15 29]]


In [ ]:
from sklearn.linear_model import LogisticRegression       #by using Logistic Regression
logmodel=LogisticRegression()

In [ ]:
logmodel.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
y_pred=logmodel.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_pred,y_test)
ac= accuracy_score(y_pred,y_test)

In [ ]:
print(cm)

[[91 15]
 [15 33]]


In [ ]:
print(ac)

0.8051948051948052


In [ ]:
from sklearn.tree import DecisionTreeClassifier     #by using Decision tree
tree_classifier=DecisionTreeClassifier()

In [ ]:
tree_classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred=tree_classifier.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_pred,y_test)
ac= accuracy_score(y_pred,y_test)

In [ ]:
print(cm)

[[83 14]
 [23 34]]


In [ ]:
print(ac)

0.7597402597402597


In [ ]:
from sklearn.ensemble import RandomForestClassifier           #by using Random Forest
classifier=RandomForestClassifier()

In [ ]:
classifier.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred=classifier.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_pred,y_test)
ac= accuracy_score(y_pred,y_test)

In [ ]:
print(ac)

0.7792207792207793


In [ ]:
print(cm)

[[89 17]
 [17 31]]


In [ ]:
my_data={'Pregnancies':2,'Glucose':143,'BloodPressure':60,'SkinThickness':23,'Insulin':0,'BMI':23,'DiabetesPedigreeFunction':0.324,'Age':27}

In [ ]:
index=[1]

In [ ]:
new_data=pd.DataFrame(my_data,index)

In [ ]:
new_data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
1            2      143             60             23        0   23   

   DiabetesPedigreeFunction  Age  
1                     0.324   27

In [ ]:
classification=logmodel.predict(new_data)

In [ ]:
print('the new customer has',classification)

the new customer has [0]
